version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      DB_CONN_STR: postgresql://dbadmin:dbsecret@postgres:5432/template_db
      # openssl rand -hex 32
      JWT_SECRET_KEY: 3e84463acdcf5ba0c0ac9dddd020780607a4d567c29b0b52f3a8979015a1d1a5
    volumes:
      - ../..:/workspaces:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    command: sleep infinity

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_DB: template_db
      POSTGRES_PASSWORD: dbsecret

volumes:
  postgres-data:
